-- MySQL의 문자 집합 설정 (UTF-8로 인코딩하도록)
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET character_set_connection=utf8mb4;

CREATE TABLE IF NOT EXISTS Quiz (
                                    quiz_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                    subject ENUM('SCIENCE', 'ECONOMY', 'HISTORY', 'PREVIEW', 'ENG_WORD', 'HEALTH') NOT NULL,
                                    type ENUM('MC', 'TF', 'SA') NOT NULL,
                                    level ENUM('EZ', 'MD', 'HD') NOT NULL,
                                    question TEXT NOT NULL,
                                    correctAnswer VARCHAR(255) NOT NULL,
                                    optionA VARCHAR(255),
                                    optionB VARCHAR(255),
                                    optionC VARCHAR(255),
                                    optionD VARCHAR(255),
                                    optionE VARCHAR(255)
);


-- Quiz 테이블에 데이터 삽입
-- 과학
INSERT INTO Quiz (subject, type, level, question, correctAnswer, optionA, optionB, optionC, optionD, optionE) VALUES
                                                                                                                  ('SCIENCE', 'MC', 'EZ', '태양계에서 가장 큰 행성은?', '목성', '지구', '화성', '금성', '목성', '토성'),
                                                                                                                  ('SCIENCE', 'MC', 'EZ', '빛의 속도는 약 몇 km/s인가?', '300,000 km/s', '30,000 km/s', '300,000 km/s', '3,000 km/s', '300 km/s', '30 km/s'),
                                                                                                                  ('SCIENCE', 'MC', 'EZ', '식물의 광합성에 필요한 기체는?', '이산화탄소', '산소', '이산화탄소', '질소', '수소', '메탄'),
                                                                                                                  ('SCIENCE', 'MC', 'EZ', '원자번호가 1인 원소는?', '수소', '산소', '헬륨', '수소', '탄소', '질소'),
                                                                                                                  ('SCIENCE', 'MC', 'EZ', '우리 눈에 보이는 빛의 파장 범위는 대략 얼마인가?', '400-700 nm', '300-400 nm', '400-700 nm', '700-1000 nm', '100-300 nm', '10-100 nm'),
                                                                                                                  ('SCIENCE', 'MC', 'EZ', '대기압의 단위로 흔히 사용되는 것은?', '파스칼', '킬로그램', '미터', '파스칼', '리터', '암페어'),
                                                                                                                  ('SCIENCE', 'MC', 'EZ', '물체가 물에 뜨는 이유는 무엇 때문인가요?', '밀도', '밀도', '온도', '색깔', '질량', '부피'),
                                                                                                                  ('SCIENCE', 'MC', 'EZ', '전기의 단위는?', '암페어', '볼트', '암페어', '옴', '와트', '킬로그램'),
                                                                                                                  ('SCIENCE', 'MC', 'EZ', '식물의 세포벽을 구성하는 물질은?', '셀룰로오스', '셀룰로오스', '키틴', '단백질', '지질', '전분'),
                                                                                                                  ('SCIENCE', 'MC', 'EZ', '인간의 체온을 조절하는 기관은?', '피부', '간', '심장', '피부', '폐', '신장'),

                                                                                                                  ('SCIENCE', 'MC', 'MD', '원소 주기율표에서 6번째 원소는?', '탄소', '산소', '탄소', '질소', '수소', '헬륨'),
                                                                                                                  ('SCIENCE', 'MC', 'MD', '중력 가속도의 값은 약 몇 m/s²인가?', '9.8 m/s²', '9.8 m/s²', '10 m/s²', '8.9 m/s²', '9.1 m/s²', '10.5 m/s²'),
                                                                                                                  ('SCIENCE', 'MC', 'MD', '지구의 핵이 주로 구성된 두 가지 원소는?', '철과 니켈', '철과 니켈', '철과 구리', '니켈과 아연', '철과 마그네슘', '구리와 아연'),
                                                                                                                  ('SCIENCE', 'MC', 'MD', '광합성 과정에서 생성되는 산소는 어디에서 유래하는가?', '물', '이산화탄소', '물', '포도당', '빛', '토양'),
                                                                                                                  ('SCIENCE', 'MC', 'MD', '지구에서 가장 흔한 금속은?', '철', '금', '철', '알루미늄', '구리', '은'),
                                                                                                                  ('SCIENCE', 'MC', 'MD', '원자의 중심에 위치한 입자는?', '양성자', '전자', '양성자', '중성자', '중성미자', '쿼크'),
                                                                                                                  ('SCIENCE', 'MC', 'MD', '지구의 대기는 몇 개의 주요 층으로 나뉘어 있나요?', '5개', '2개', '3개', '4개', '5개', '6개'),
                                                                                                                  ('SCIENCE', 'MC', 'MD', '포유류의 폐에서 일어나는 가스 교환은 주로 어디서 이루어지나요?', '폐포', '기관지', '기관', '폐포', '기관지 끝', '폐동맥'),
                                                                                                                  ('SCIENCE', 'MC', 'MD', '아이작 뉴턴이 제시한 운동 법칙 중 첫 번째 법칙은?', '관성의 법칙', '가속도의 법칙', '작용-반작용 법칙', '관성의 법칙', '만유인력의 법칙', '상대성 법칙'),
                                                                                                                  ('SCIENCE', 'MC', 'MD', '태양계에서 해왕성의 위성 중 가장 큰 것은?', '트리톤', '타이탄', '이오', '트리톤', '가니메데', '칼리스토'),

                                                                                                                  ('SCIENCE', 'MC', 'HD', '다이아몬드의 결정 구조는?', '면심입방구조', '체심입방구조', '면심입방구조', '육방밀집구조', '정육면체구조', '사방정계구조'),
                                                                                                                  ('SCIENCE', 'MC', 'HD', '일반상대성 이론에서 질량이 시공간을 어떻게 변화시키는가?', '질량은 시공간을 휘게 한다', '질량은 시공간을 늘린다', '질량은 시공간을 휘게 한다', '질량은 시공간을 줄인다', '질량은 시공간을 변형시키지 않는다', '질량은 시공간을 회전시킨다'),
                                                                                                                  ('SCIENCE', 'MC', 'HD', '양자역학에서 파동함수의 절대값 제곱은 무엇을 나타내는가?', '입자의 위치 확률 밀도', '입자의 에너지', '입자의 운동량', '입자의 위치 확률 밀도', '입자의 스핀', '입자의 전하'),
                                                                                                                  ('SCIENCE', 'MC', 'HD', 'DNA 복제에서 DNA 가닥을 분리하는 효소는?', '헬리케이스', 'DNA 리가아제', 'DNA 폴리메라제', '헬리케이스', '프라이메이스', '톱오이소머라제'),
                                                                                                                  ('SCIENCE', 'MC', 'HD', '전자기파 스펙트럼에서 파장이 가장 짧은 것은?', '감마선', '가시광선', '자외선', '적외선', '감마선', 'X선'),
                                                                                                                  ('SCIENCE', 'MC', 'HD', '미생물학에서 \'그람 염색\'은 무엇을 분류하는데 사용되는가?', '박테리아', '바이러스', '균류', '박테리아', '원생생물', '효소'),
                                                                                                                  ('SCIENCE', 'MC', 'HD', '천문학에서 중성자별이 형성되는 주된 이유는?', '초신성 폭발', '초신성 폭발', '블랙홀 형성', '항성의 붕괴', '항성의 진화', '행성의 충돌'),
                                                                                                                  ('SCIENCE', 'MC', 'HD', '양자역학에서 불확정성 원리는 누구에 의해 제안되었는가?', '하이젠베르크', '아인슈타인', '슈뢰딩거', '하이젠베르크', '보어', '디랙'),
                                                                                                                  ('SCIENCE', 'MC', 'HD', '비타민 C의 화학 명칭은?', '아스코르빈산', '리보플라빈', '나이아신', '아스코르빈산', '피리독신', '티아민'),
                                                                                                                  ('SCIENCE', 'MC', 'HD', '원자핵을 구성하는 기본 입자는?', '양성자와 중성자', '전자', '양성자', '중성자', '양성자와 중성자', '양성자와 전자'),

                                                                                                                  ('SCIENCE', 'TF', 'EZ', '지구의 자전축은 약 23.5도 기울어져 있다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'EZ', '태양은 주로 수소와 헬륨으로 구성되어 있다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'EZ', '전기는 전자의 이동으로 발생한다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'EZ', '다이아몬드는 순수한 탄소로 구성되어 있다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'EZ', '지구의 핵은 주로 철과 니켈로 구성되어 있다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'EZ', '지구의 자전 속도는 적도에서 가장 빠르다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'EZ', '모든 금속은 상온에서 고체 상태이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'EZ', '인간의 골격은 약 206개의 뼈로 구성되어 있다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'EZ', '우리가 마시는 물의 대부분은 순수한 H2O이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'EZ', '철은 자성을 띄는 금속이다.', 'True', 'True', 'False', NULL, NULL, NULL),

                                                                                                                  ('SCIENCE', 'TF', 'MD', 'DNA는 세포의 핵 안에 있다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'MD', '플루토늄은 자연적으로 발생하는 원소이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'MD', '바람은 고기압에서 저기압으로 불어간다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'MD', '헬륨은 가장 가벼운 원소이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'MD', '기체는 액체보다 밀도가 높다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'MD', '유전 정보는 RNA에서 DNA로 전달된다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'MD', '대류는 액체와 기체에서만 발생한다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'MD', '화산활동은 판구조론과 관련이 있다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'MD', '열은 항상 차가운 물체에서 뜨거운 물체로 이동한다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'MD', '염산은 강한 염기이다.', 'False', 'True', 'False', NULL, NULL, NULL),

                                                                                                                  ('SCIENCE', 'TF', 'HD', '초전도체는 절대 영도에서 무한 저항을 가진다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'HD', '암흑 물질은 전자기파를 방출하거나 흡수하지 않는다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'HD', '상대성이론에 따르면, 빛의 속도는 진공에서만 일정하다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'HD', '양자 역학에서는 입자의 정확한 위치와 운동량을 동시에 측정할 수 없다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'HD', '중성미자는 매우 높은 질량을 가진 입자이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'HD', '지구의 핵은 고체와 액체로 구성되어 있다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'HD', '양자 터널링은 입자가 장벽을 넘어갈 확률을 가진 현상이다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'HD', 'RNA는 유전 정보의 저장을 주된 기능으로 한다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'HD', '엔트로피는 시스템의 무질서도를 나타내는 척도이다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'TF', 'HD', '플라즈마는 물질의 네 번째 상태이다.', 'True', 'True', 'False', NULL, NULL, NULL),

                                                                                                                  ('SCIENCE', 'SA', 'EZ', '기체를 액체로 변하게 하는 과정을 무엇이라고 하나요?', '응결', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'EZ', '식물에서 물과 영양분을 흡수하는 부분은 무엇인가요?', '뿌리', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'EZ', '컴퓨터의 중앙 처리 장치를 무엇이라고 하나요?', 'CPU', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'EZ', '전구에서 빛을 내는 부분을 무엇이라고 하나요?', '필라멘트', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'EZ', '우리 몸의 70% 이상을 차지하는 것은 무엇인가요?', '물', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'EZ', '햇빛 속의 자외선은 피부에 어떤 비타민을 생성하게 하나요?', '비타민 D', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'EZ', '사람의 몸에서 이산화탄소를 배출하는 기관은 무엇인가요?', '폐', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'EZ', '바닷물은 주로 어떤 물질로 인해 짠맛을 내나요?', '소금', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'EZ', '사람의 몸에서 산소를 운반하는 세포는 무엇인가요?', '적혈구', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'EZ', '지구의 가장 바깥쪽 층을 무엇이라고 하나요?', '지각', NULL, NULL, NULL, NULL, NULL),

                                                                                                                  ('SCIENCE', 'SA', 'MD', '태양의 주 에너지원은 무엇인가요?', '핵융합', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'MD', '기체를 액체로 변환하는 과정을 무엇이라 하나요?', '응축', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'MD', '전지에서 화학 에너지를 전기 에너지로 변환하는 장치는 무엇인가요?', '배터리', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'MD', '지구의 표면에서 가장 많은 물질 상태는 무엇인가요?', '액체', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'MD', '컴퓨터에서 정보를 일시적으로 저장하는 장치는 무엇인가요?', 'RAM (램)', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'MD', '자동차에서 연료를 연소시켜 동력을 얻는 장치는 무엇인가요?', '엔진', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'MD', '식물의 광합성에 필요한 빛의 주된 원천은 무엇인가요?', '태양', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'MD', '음식물의 소화와 영양소 흡수를 주로 담당하는 기관은 무엇인가요?', '소장', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'MD', '지구의 대기를 구성하는 주요 층 중 하나는 무엇인가요?', '성층권', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'MD', '지구에서 가장 깊은 해양은 무엇인가요?', '마리아나 해구', NULL, NULL, NULL, NULL, NULL),

                                                                                                                  ('SCIENCE', 'SA', 'HD', '지구의 대기권 중 가장 외부에 있는 층은 무엇인가요?', '외기권', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'HD', '세포막을 구성하는 주된 물질은 무엇인가요?', '인지질', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'HD', '탄수화물을 단당류로 분해하는 효소는 무엇인가요?', '아밀라', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'HD', '화학 반응에서 반응 속도를 높이는 물질은 무엇인가요?', '촉매', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'HD', '행성의 궤도를 설명하는 법칙을 제안한 과학자는 누구인가요?', '케플러', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'HD', '음극선 관 실험을 통해 전자를 발견한 과학자는 누구인가요?', '톰슨', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'HD', '양자역학의 불확정성 원리를 제안한 과학자는 누구인가요?', '하이젠베르크', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'HD', '원자의 중심에 위치한 양성자와 중성자의 집합체를 무엇이라 하나요?', '원자핵', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'HD', '상대성이론을 제안한 과학자는 누구인가요?', '아인슈타인', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('SCIENCE', 'SA', 'HD', '기체의 부피와 온도 관계를 설명하는 법칙은 무엇인가요?', '샤를의 법칙', NULL, NULL, NULL, NULL, NULL);



-- 경제
INSERT INTO Quiz (subject, type, level, question, correctAnswer, optionA, optionB, optionC, optionD, optionE) VALUES
                                                                                                                  ('ECONOMY', 'MC', 'EZ', '경제학에서 "수요"란 무엇을 의미하는가?', '소비자의 구매 의사', '공급', '시장', '소비자의 구매 의사', '생산자의 판매 의사', '정부의 정책'),
                                                                                                                  ('ECONOMY', 'MC', 'EZ', '화폐의 기본 기능 중 하나는 무엇인가?', '교환의 매개', '생산의 수단', '교환의 매개', '투자 수단', '정부의 도구', '소비의 기준'),
                                                                                                                  ('ECONOMY', 'MC', 'EZ', '물가가 지속적으로 상승하는 현상을 무엇이라 하나요?', '인플레이션', '경기후퇴', '디플레이션', '인플레이션', '불황', '경제성장'),
                                                                                                                  ('ECONOMY', 'MC', 'EZ', '중앙은행이 화폐 공급량을 조절하는 정책은 무엇인가요?', '통화정책', '재정정책', '무역정책', '통화정책', '가격정책', '금융정책'),
                                                                                                                  ('ECONOMY', 'MC', 'EZ', '정부가 재정 적자를 메우기 위해 발행하는 것은 무엇인가요?', '채권', '주식', '채권', '화폐', '금', '부동산'),
                                                                                                                  ('ECONOMY', 'MC', 'EZ', '수출보다 수입이 많은 상태를 무엇이라고 하나요?', '무역적자', '무역흑자', '무역균형', '무역적자', '무역보호', '무역수지'),
                                                                                                                  ('ECONOMY', 'MC', 'EZ', '물가 상승률을 측정하는 지표는?', 'CPI', 'GDP', 'GNP', 'CPI', 'PPI', 'NNP'),
                                                                                                                  ('ECONOMY', 'MC', 'EZ', '경제에서 "수요의 법칙"이란?', '가격이 오를 때 수요가 감소한다', '가격이 오를 때 수요가 증가한다', '가격이 오를 때 수요가 감소한다', '공급이 증가할 때 수요가 증가한다', '공급이 감소할 때 수요가 감소한다', '가격과 수요는 무관하다'),
                                                                                                                  ('ECONOMY', 'MC', 'EZ', '기업이 이익을 내기 위해 발생시키는 비용을 무엇이라 하나요?', '경비', '매출', '이윤', '경비', '투자', '배당'),
                                                                                                                  ('ECONOMY', 'MC', 'EZ', '시장 경제에서 가격이 형성되는 방식은?', '수요와 공급', '정부의 결정', '중앙은행의 결정', '수요와 공급', '기업의 결정', '국제 협정'),

                                                                                                                  ('ECONOMY', 'MC', 'MD', '이자율이 상승하면 예상되는 경제 효과는?', '투자 감소', '소비 증가', '투자 감소', '인플레이션 증가', '수출 감소', '재정 적자 증가'),
                                                                                                                  ('ECONOMY', 'MC', 'MD', '경기 침체는 일반적으로 몇 분기 연속으로 GDP가 감소하는 상태를 의미하는가?', '2분기', '1분기', '2분기', '3분기', '4분기', '5분기'),
                                                                                                                  ('ECONOMY', 'MC', 'MD', '기업의 순이익은 무엇을 의미하는가?', '총매출에서 총비용을 뺀 값', '총매출', '총비용', '총매출에서 총비용을 뺀 값', '자본금', '총자산'),
                                                                                                                  ('ECONOMY', 'MC', 'MD', '실질 GDP란 무엇을 의미하는가?', '물가 변동을 고려한 GDP', '물가 변동을 고려하지 않은 GDP', '물가 변동을 고려한 GDP', '명목 GDP와 동일한 개념', '세금 부과 후의 GDP', '수출입을 제외한 GDP'),
                                                                                                                  ('ECONOMY', 'MC', 'MD', '자유 무역 협정(FTA)이란 무엇인가?', '국가 간 무역 장벽을 낮추는 협정', '국가 간 무역을 제한하는 협정', '국가 간 무역 장벽을 낮추는 협정', '국내 산업 보호를 위한 협정', '통화 통합을 위한 협정', '환경 보호를 위한 협정'),
                                                                                                                  ('ECONOMY', 'MC', 'MD', '한 나라의 경제성장률은 무엇으로 측정되는가?', 'GDP 증가율', '실업률', '물가 상승률', 'GDP 증가율', '환율', '이자율'),
                                                                                                                  ('ECONOMY', 'MC', 'MD', '소득세는 어떤 유형의 세금인가?', '직접세', '간접세', '직접세', '소비세', '부가가치세', '환경세'),
                                                                                                                  ('ECONOMY', 'MC', 'MD', '경기 과열을 방지하기 위해 중앙은행이 취할 수 있는 조치는?', '금리 인상', '금리 인하', '금리 인상', '화폐 공급 증가', '정부 지출 증가', '세금 인하'),
                                                                                                                  ('ECONOMY', 'MC', 'MD', '투자자의 주식 보유 이유 중 하나는?', '배당금', '이자 수익', '배당금', '상품 할인가', '고정 수익', '소득세 절감'),
                                                                                                                  ('ECONOMY', 'MC', 'MD', '소비자 물가 지수(CPI)는 무엇을 측정하는가?', '소비자가 구매하는 상품과 서비스의 가격 변동', '정부 지출', '수출입 수지', '소비자가 구매하는 상품과 서비스의 가격 변동', '기업의 생산 비용', '주식 시장 지수'),

                                                                                                                  ('ECONOMY', 'MC', 'HD', '케인즈 학파는 경제 침체 시 정부의 무엇을 강조하는가?', '재정 지출', '화폐 공급', '재정 지출', '금리 인하', '세금 감면', '수출 확대'),
                                                                                                                  ('ECONOMY', 'MC', 'HD', '국제 통화 기금(IMF)은 무엇을 주로 다루는가?', '국제 금융 안정', '무역 협정', '경제 개발', '통화 정책', '국제 금융 안정', '자원 관리'),
                                                                                                                  ('ECONOMY', 'MC', 'HD', '필립스 곡선은 무엇을 설명하는가?', '물가와 실업률의 관계', '물가와 실업률의 관계', '수요와 공급의 관계', '금리와 인플레이션의 관계', 'GDP와 경제 성장의 관계', '투자와 소비의 관계'),
                                                                                                                  ('ECONOMY', 'MC', 'HD', '경제적 부가가치(EVA)는 어떤 개념을 측정하는가?', '경제적 순이익', '기업의 순이익', '경제적 순이익', '자산 가치', '주식 가치', '생산 비용'),
                                                                                                                  ('ECONOMY', 'MC', 'HD', '정부의 통화정책 중 금리 인상은 주로 어떤 효과를 기대하는가?', '인플레이션 억제', '경제 성장 촉진', '소비 증가', '인플레이션 억제', '실업률 감소', '수출 증가'),
                                                                                                                  ('ECONOMY', 'MC', 'HD', '스태그플레이션은 어떤 경제 상태를 나타내는가?', '경기 침체와 인플레이션 동반', '경제 성장과 인플레이션 동반', '경기 침체와 물가 하락 동반', '경기 침체와 인플레이션 동반', '경제 성장과 물가 하락 동반', '경기 회복과 물가 안정 동반'),
                                                                                                                  ('ECONOMY', 'MC', 'HD', '지니 계수는 무엇을 측정하는 지표인가?', '소득 불평등', '경제 성장률', '실업률', '소득 불평등', '물가 상승률', '무역 수지'),
                                                                                                                  ('ECONOMY', 'MC', 'HD', '금융위기 후 은행의 자본건전성을 강화하기 위해 도입된 국제 기준은?', '바젤 III', '바젤 I', '바젤 II', '바젤 III', '바젤 IV', '바젤 V'),
                                                                                                                  ('ECONOMY', 'MC', 'HD', '화폐의 유통 속도는 무엇을 의미하는가?', '화폐가 교환되는 빈도', '화폐 발행량', '화폐가 교환되는 빈도', '화폐의 가치', '화폐의 구매력', '화폐의 희소성'),
                                                                                                                  ('ECONOMY', 'MC', 'HD', '경제적 잉여는 무엇을 의미하는가?', '소비자와 생산자가 누리는 이익', '생산비와 판매가의 차이', '소비자와 생산자가 누리는 이익', '총수입과 총지출의 차이', '정부 수입과 지출의 차이', '수출과 수입의 차이'),

                                                                                                                  ('ECONOMY', 'TF', 'EZ', '인플레이션은 물가가 하락하는 현상이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'EZ', '통화정책은 정부의 예산을 조절하는 정책이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'EZ', '수요가 증가하면 가격이 상승할 수 있다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'EZ', '금리가 낮아지면 대출 수요가 증가할 수 있다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'EZ', '소비자 물가 지수는 소비자가 구매하는 상품과 서비스의 가격 변동을 측정한다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'EZ', '실업률이 높아지면 경제 활동이 활발해진다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'EZ', '중앙은행은 화폐 발행을 담당한다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'EZ', '공급이 증가하면 가격이 상승할 수 있다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'EZ', '시장 경제에서는 정부가 가격을 결정한다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'EZ', '경기 침체는 경제 활동이 둔화되는 현상이다.', 'True', 'True', 'False', NULL, NULL, NULL),

                                                                                                                  ('ECONOMY', 'TF', 'MD', '수요가 증가할 때 발생할 수 있는 현상은 가격 상승이다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'MD', '환율이 상승할 때, 수출업체에 미치는 영향은 부정적이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'MD', '이자율이 상승하면 예상되는 경제 효과는 투자 감소이다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'MD', '실질 GDP는 물가 변동을 고려하지 않은 GDP이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'MD', '공급 곡선이 오른쪽으로 이동하면 공급 증가를 의미한다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'MD', '자유 무역 협정(FTA)은 국가 간 무역 장벽을 낮추는 협정이다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'MD', '공공재의 예로 적합한 것은 개인 주택이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'MD', '공급 과잉이 발생하면 가격은 상승한다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'MD', '수출보다 수입이 많은 상태를 무역적자라고 한다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'MD', '경기 과열을 방지하기 위해 중앙은행이 취할 수 있는 조치는 금리 인하이다.', 'False', 'True', 'False', NULL, NULL, NULL),

                                                                                                                  ('ECONOMY', 'TF', 'HD', '재정정책은 정부가 경제 성장을 촉진하기 위해 사용하는 주요 도구 중 하나이다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'HD', '미시경제학은 국가 전체의 경제 활동을 다루는 학문이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'HD', '케인즈 경제학은 수요 측면의 경제 정책을 중시한다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'HD', '고정환율제도는 시장의 수요와 공급에 따라 환율이 변동하는 제도이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'HD', '노동 생산성 증가는 일반적으로 실업률 감소를 초래한다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'HD', '경기 과열을 방지하기 위해 정부가 채택할 수 있는 조치는 금리 인하이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'HD', '양적 완화는 중앙은행이 자산을 매입하여 통화 공급을 늘리는 정책이다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'HD', '금융위기 후 바젤 III는 은행의 자본 건전성을 강화하기 위해 도입된 국제 기준이다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'HD', '탄력성 개념에서 수요의 가격 탄력성이 1보다 작다면 수요는 비탄력적이다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'TF', 'HD', '외환 보유고는 주로 국내 통화의 가치를 안정시키기 위해 사용된다.', 'True', 'True', 'False', NULL, NULL, NULL),

                                                                                                                  ('ECONOMY', 'SA', 'EZ', '물가가 지속적으로 상승하는 현상은?', '인플레이션', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'EZ', '중앙은행이 화폐 공급량을 조절하는 정책은?', '통화정책', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'EZ', '정부가 재정 적자를 메우기 위해 발행하는 것은?', '채권', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'EZ', '수출보다 수입이 많은 상태를 무엇이라고 하나요?', '무역적자', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'EZ', '비용이 매출보다 클 때 발생하는 현상은?', '적자', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'EZ', '수요가 증가할 때 발생할 수 있는 현상은?', '가격 상승', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'EZ', '가격이 하락하여 경제 활동이 위축되는 현상은?', '디플레이션', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'EZ', '정부가 경제 성장을 위해 가장 많이 사용하는 정책은?', '통화정책', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'EZ', '국제 무역에서 사용되는 통화는 주로 무엇인가요?', '달러', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'EZ', '소비자 물가 지수는 무엇을 측정하는가?', '물가 상승률', NULL, NULL, NULL, NULL, NULL),

                                                                                                                  ('ECONOMY', 'SA', 'MD', '중앙은행이 화폐 공급량을 조절하는 정책은 무엇인가요?', '통화정책', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'MD', '정부가 재정 적자를 메우기 위해 발행하는 것은 무엇인가요?', '채권', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'MD', '수출보다 수입이 많은 상태를 무엇이라고 하나요?', '무역적자', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'MD', '기업이 이익을 내기 위해 발생시키는 비용을 무엇이라고 하나요?', '경비', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'MD', '소비자 물가 지수는 무엇을 측정하는가?', '물가 상승률 증가', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'MD', '물가가 상승할 때 일반적으로 나타나는 현상은 무엇인가요?', '인플레이션', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'MD', '경기 침체는 일반적으로 몇 분기 연속으로 GDP가 감소하는 상태를 의미하나요?', '2분기', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'MD', '소득세는 어떤 유형의 세금인가요?', '직접세', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'MD', '경제학에서 "선택하지 않은 대안의 가치"이란 무엇을 의미하는가?', '기회비용', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'MD', '외환 시장에서 통화의 가치는 무엇에 의해 결정되는가요?', '수요와 공급', NULL, NULL, NULL, NULL, NULL),

                                                                                                                  ('ECONOMY', 'SA', 'HD', '주식시장에서 주가의 장기적 상승 추세를 무엇이라 하나요?', '강세장', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'HD', '정부가 재정 적자를 메우기 위해 발행하는 것은 무엇인가요?', '국채', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'HD', '환율 변동이 수출입에 미치는 영향을 분석하는 학문은 무엇인가요?', '국제경제학', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'HD', '화폐의 유통 속도를 측정하는 지표는 무엇인가요?', '화폐 유통 속도', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'HD', '비트코인과 같은 디지털 통화는 어떤 기술에 기반을 두고 있나요?', '블록체인', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'HD', '통화주의 경제학자 밀턴 프리드먼이 주장한 중요한 개념은 무엇인가요?', '통화 공급의 중요성', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'HD', '무역 장벽 중 하나로, 수입품에 부과하는 세금은 무엇인가요?', '관세', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'HD', '국가 간 무역 장벽을 낮추는 협정은 무엇인가요?', '자유무역협정(FTA)', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'HD', '케인즈 경제학에서 경제 침체 시 권장되는 정책은 무엇인가요?', '재정 지출 확대', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('ECONOMY', 'SA', 'HD', '경제 주체 간의 상호작용을 분석하는 학문은 무엇인가요?', '거시 경제학', NULL, NULL, NULL, NULL, NULL);


-- 역사
INSERT INTO Quiz (subject, type, level, question, correctAnswer, optionA, optionB, optionC, optionD, optionE) VALUES
                                                                                                                  ('HISTORY', 'MC', 'EZ', '미국의 초대 대통령은 누구인가요?', '조지 워싱턴', '토머스 제퍼슨', '존 애덤스', '조지 워싱턴', '제임스 매디슨', '앤드류 잭슨'),
                                                                                                                  ('HISTORY', 'MC', 'EZ', '프랑스 혁명은 몇 년에 시작되었나요?', '1789년', '1785년', '1787년', '1789년', '1791년', '1793년'),
                                                                                                                  ('HISTORY', 'MC', 'EZ', '영국의 대표적인 전통 축제는 무엇인가요?', '크리스마스', '할로윈', '추수감사절', '크리스마스', '디왈리', '송크란'),
                                                                                                                  ('HISTORY', 'MC', 'EZ', '로마 제국의 첫 번째 황제는 누구인가요?', '아우구스투스', '줄리어스 시저', '네로', '트라야누스', '아우구스투스', '하드리아누스'),
                                                                                                                  ('HISTORY', 'MC', 'EZ', '미국 독립 선언문이 발표된 날은?', '1776년 7월 4일', '1774년 7월 4일', '1775년 7월 4일', '1776년 7월 4일', '1777년 7월 4일', '1778년 7월 4일'),
                                                                                                                  ('HISTORY', 'MC', 'EZ', '한국의 첫 번째 대통령은 누구인가요?', '이승만', '박정희', '김대중', '노무현', '이승만', '김영삼'),
                                                                                                                  ('HISTORY', 'MC', 'EZ', '세계 1차 대전이 시작된 해는?', '1914년', '1912년', '1914년', '1916년', '1918년', '1920년'),
                                                                                                                  ('HISTORY', 'MC', 'EZ', '로마 제국의 멸망은 몇 년에 일어났나요?', '476년', '354년', '410년', '476년', '500년', '526년'),
                                                                                                                  ('HISTORY', 'MC', 'EZ', '콜럼버스가 아메리카 대륙을 발견한 해는?', '1492년', '1490년', '1492년', '1494년', '1496년', '1498년'),
                                                                                                                  ('HISTORY', 'MC', 'EZ', '영국의 엘리자베스 2세 여왕이 즉위한 해는?', '1952년', '1945년', '1948년', '1952년', '1955년', '1960년'),

                                                                                                                  ('HISTORY', 'MC', 'MD', '미국 남북전쟁의 시작을 알린 전투는?', '섬터 요새 전투', '게티즈버그 전투', '샤일로 전투', '섬터 요새 전투', '앤티텀 전투', '빅스버그 전투'),
                                                                                                                  ('HISTORY', 'MC', 'MD', '영국에서 산업혁명이 시작된 주요 원인은?', '자원의 풍부', '노동력 부족', '자원의 풍부', '외국의 침략', '종교 갈등', '기후 변화'),
                                                                                                                  ('HISTORY', 'MC', 'MD', '대항해시대를 연 중요한 사건은?', '크리스토퍼 콜럼버스의 신대륙 발견', '크리스토퍼 콜럼버스의 신대륙 발견', '마젤란의 세계 일주', '바스코 다 가마의 인도 항로 개척', '제임스 쿡의 오스트레일리아 발견', '마르코 폴로의 동방 여행'),
                                                                                                                  ('HISTORY', 'MC', 'MD', '이탈리아의 통일을 이끈 지도자는?', '가리발디', '마치니', '카보우르', '가리발디', '무솔리니', '빅토르 엠마누엘 2세'),
                                                                                                                  ('HISTORY', 'MC', 'MD', '알렉산더 대왕이 동방 원정을 시작한 나라는?', '페르시아', '페르시아', '인도', '이집트', '로마', '중국'),
                                                                                                                  ('HISTORY', 'MC', 'MD', '러시아 혁명에서 볼셰비키가 이끈 주요 인물은?', '레닌', '레닌', '트로츠키', '스탈린', '크루프스카야', '체카'),
                                                                                                                  ('HISTORY', 'MC', 'MD', '히틀러가 주도한 독일의 정당은?', '나치당', '공산당', '사회민주당', '나치당', '자유민주당', '보수당'),
                                                                                                                  ('HISTORY', 'MC', 'MD', '세계 2차 대전에서 연합국의 주요 지도자는?', '스탈린', '히틀러', '스탈린', '무솔리니', '프랑코', '히로히토'),
                                                                                                                  ('HISTORY', 'MC', 'MD', '독일의 베를린 장벽이 붕괴된 해는?', '1989년', '1987년', '1988년', '1989년', '1990년', '1991년'),
                                                                                                                  ('HISTORY', 'MC', 'MD', '프랑스 혁명의 주요 구호는?', '자유, 평등, 형제애', '자유, 평등, 형제애', '평화, 사랑, 연대', '정의, 평등, 자비', '자유, 평화, 형제애', '민주, 평등, 자유'),

                                                                                                                  ('HISTORY', 'MC', 'HD', '페르시아 전쟁에서 그리스 연합군이 페르시아 군을 물리친 결정적인 전투는 무엇인가요?', '플라타이아 전투', '마라톤 전투', '살라미스 해전', '플라타이아 전투', '테르모필레 전투', '아르테미시움 해전'),
                                                                                                                  ('HISTORY', 'MC', 'HD', '1871년 독일 제국을 통일한 주도적인 인물은 누구인가요?', '오토 폰 비스마르크', '오토 폰 비스마르크', '빌헬름 1세', '프리드리히 3세', '빌헬름 2세', '프란츠 요제프 1세'),
                                                                                                                  ('HISTORY', 'MC', 'HD', '프랑스 혁명 중 "테르미도르의 반동"으로 처형된 인물은 누구인가요?', '막시밀리앙 로베스피에르', '막시밀리앙 로베스피에르', '조르주 당통', '장 폴 마라', '자크 루이 다비드', '나폴레옹 보나파르트'),
                                                                                                                  ('HISTORY', 'MC', 'HD', '미국 남북전쟁의 최후의 전투는 무엇인가요?', '애플러매톡스 코트하우스 전투', '게티즈버그 전투', '샤일로 전투', '피터스버그 전투', '애틀랜타 전투', '애플러매톡스 코트하우스 전투'),
                                                                                                                  ('HISTORY', 'MC', 'HD', '프랑스와 프로이센의 전쟁에서 프로이센이 승리한 결정적인 전투는 무엇인가요?', '세당 전투', '제나-아우어슈테트 전투', '쿨름 전투', '발미 전투', '세당 전투', '워털루 전투'),
                                                                                                                  ('HISTORY', 'MC', 'HD', '세계 2차 대전 중 노르망디 상륙작전이 일어난 날짜는 언제인가요?', '1944년 6월 6일', '1944년 4월 6일', '1944년 5월 6일', '1944년 6월 6일', '1944년 7월 6일', '1944년 8월 6일'),
                                                                                                                  ('HISTORY', 'MC', 'HD', '르네상스 시기 "천문학 혁명"을 일으킨 인물은 누구인가요?', '니콜라우스 코페르니쿠스', '니콜라우스 코페르니쿠스', '갈릴레오 갈릴레이', '요하네스 케플러', '아이작 뉴턴', '타이코 브라헤'),
                                                                                                                  ('HISTORY', 'MC', 'HD', '로마 제국의 황제였던 네로는 어떤 사건으로 유명한가요?', '로마 대화재', '카이사르의 암살', '로마 대화재', '푸테올리 전투', '콘스탄티노플 건설', '피사의 탑 건설'),
                                                                                                                  ('HISTORY', 'MC', 'HD', '제1차 세계 대전 중 발칸 반도를 둘러싼 주요 전투는 무엇인가요?', '갈리폴리 전투', '솜 전투', '마른 전투', '갈리폴리 전투', '베르됭 전투', '캄브레 전투'),
                                                                                                                  ('HISTORY', 'MC', 'HD', '1917년 러시아 혁명에서 볼셰비키가 주도한 혁명은 무엇인가요?', '10월 혁명', '2월 혁명', '10월 혁명', '3월 혁명', '11월 혁명', '12월 혁명'),

                                                                                                                  ('HISTORY', 'TF', 'EZ', '독일의 재통일은 1990년에 이루어졌다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'EZ', '콜럼버스는 1492년에 아메리카 대륙을 발견했다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'EZ', '나폴레옹은 1804년에 프랑스의 황제가 되었다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'EZ', '미국 독립선언문은 1776년에 발표되었다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'EZ', '영국의 왕 헨리 8세는 여섯 명의 부인을 두었다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'EZ', '세계 1차 대전은 1914년에 시작되었다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'EZ', '엘리자베스 2세 여왕은 1952년에 즉위했다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'EZ', '프랑스의 루이 14세는 베르사유 궁전을 건설했다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'EZ', '미국의 노예 해방 선언은 에이브러햄 링컨이 했다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'EZ', '한국 전쟁은 1953년에 끝났다.', 'True', 'True', 'False', NULL, NULL, NULL),

                                                                                                                  ('HISTORY', 'TF', 'MD', '중국의 진시황은 만리장성을 건설했다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'MD', '독일의 베를린 장벽은 1989년에 붕괴되었다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'MD', '알렉산더 대왕은 페르시아를 정복했다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'MD', '중국의 문화 대혁명은 마오쩌둥에 의해 주도되었다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'MD', '이탈리아의 르네상스 시대 대표적인 예술가는 레오나르도 다 빈치이다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'MD', '프랑스 혁명 중에 인권 선언문이 발표되었다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'MD', '영국의 대처리즘은 마거릿 대처에 의해 주도되었다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'MD', '대항해시대는 크리스토퍼 콜럼버스의 신대륙 발견으로 시작되었다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'MD', '영국의 산업혁명은 19세기에 시작되었다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'MD', '미국의 독립전쟁을 이끈 인물은 벤자민 프랭클린이다.', 'False', 'True', 'False', NULL, NULL, NULL),

                                                                                                                  ('HISTORY', 'TF', 'HD', '제2차 세계 대전 중 독일은 폴란드를 침공하며 전쟁을 시작했다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'HD', '영국의 왕 헨리 8세는 네 명의 부인을 두었다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'HD', '로마 제국의 수도는 콘스탄티노플이었다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'HD', '세계 1차 대전은 사라예보 사건으로 시작되었다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'HD', '프랑스의 루이 14세는 베르사유 궁전을 건설했다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'HD', '미국 대공황은 1929년에 시작되었다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'HD', '로마 제국은 476년에 멸망했다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'HD', '중국의 문화 대혁명은 1966년에 시작되었다.', 'True', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'HD', '미국의 독립전쟁을 이끈 인물은 벤자민 프랭클린이다.', 'False', 'True', 'False', NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'TF', 'HD', '세계 2차 대전의 연합국 주요 지도자는 스탈린이었다.', 'True', 'True', 'False', NULL, NULL, NULL),

                                                                                                                  ('HISTORY', 'SA', 'EZ', '미국의 초대 대통령은 누구인가요?', '조지 워싱턴', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'EZ', '이집트 피라미드를 건설한 왕조는 무엇인가요?', '제4왕조', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'EZ', '대한민국의 임시정부가 수립된 해는 언제인가요?', '1919년', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'EZ', '중국의 첫 번째 황제는 누구인가요?', '진시황', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'EZ', '세계 1차 대전이 시작된 해는 언제인가요?', '1914년', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'EZ', '한국 전쟁이 시작된 해는 언제인가요?', '1950년', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'EZ', '히로시마에 원자폭탄이 투하된 해는 언제인가요?', '1945년', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'EZ', '프랑스의 대표적인 혁명은 무엇인가요?', '프랑스 혁명', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'EZ', '영국의 산업혁명이 시작된 시기는 몇 세기인가요?', '18세기', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'EZ', '로마 제국의 첫 번째 황제는 누구인가요?', '아우구스투스', NULL, NULL, NULL, NULL, NULL),

                                                                                                                  ('HISTORY', 'SA', 'MD', '중국의 문화 대혁명을 주도한 인물은 누구인가요?', '마오쩌둥', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'MD', '중국의 만리장성을 건설한 황제는 누구인가요?', '진시황', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'MD', '영국의 대처리즘을 주도한 정치인은 누구인가요?', '마거릿 대처', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'MD', '히틀러가 주도한 독일의 정당은 무엇인가요?', '나치당', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'MD', '대한민국의 초대 대통령은 누구인가요?', '이승만', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'MD', '영국의 대표적인 산업도시는 어디인가요?', '맨체스터', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'MD', '프랑스 혁명 중 생긴 문서는 무엇인가요?', '인권 선언문', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'MD', '대한민국의 건국일은 언제인가요?(0000년 0월 0일)', '1948년 8월 15일', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'MD', '나폴레옹 전쟁의 마지막 전투는 무엇인가요?', '워털루 전투', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'MD', '세계 1차 대전이 끝난 조약은 무엇인가요?', '베르사유 조약', NULL, NULL, NULL, NULL, NULL),

                                                                                                                  ('HISTORY', 'SA', 'HD', '미국 독립전쟁 중 1781년에 결정적인 승리를 거둔 전투는 무엇인가요?', '요크타운 전투', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'HD', '중세 유럽에서 "흑사병"이 대규모로 발생한 시기는 언제인가요?', '14세기', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'HD', '일본 제국의 러일 전쟁 승리 후 체결된 조약은 무엇인가요?', '포츠머스 조약', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'HD', '중국의 송나라를 멸망시킨 몽골 제국의 황제는 누구인가요?', '쿠빌라이 칸', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'HD', '프랑스와 프로이센의 전쟁에서 프로이센이 승리한 결정적인 전투는 무엇인가요?', '세당 전투', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'HD', '일본의 에도 막부를 끝내고 메이지 유신을 시작한 인물은 누구인가요?', '도쿠가와 요시노부', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'HD', '베트남 전쟁 중 1968년에 발생한 대규모 공세는 무엇인가요?', '테트 공세', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'HD', '크리미아 전쟁에서 활약한 유명한 간호사는 누구인가요?', '나이팅게일', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'HD', '1917년 러시아 혁명에서 볼셰비키가 주도한 혁명은 무엇인가요?', '10월 혁명', NULL, NULL, NULL, NULL, NULL),
                                                                                                                  ('HISTORY', 'SA', 'HD', '제2차 세계 대전 중 일본의 항복을 이끌어낸 결정적인 사건은?', '히로시마와 나가사키 원폭 투하', NULL, NULL, NULL, NULL, NULL);
